gcc 'scheme_imp.c' -o 'scheme_imp.o' -c  -fno-strict-aliasing -fwrapv -fno-common -DHAVE_CHICKEN_CONFIG_H -DC_ENABLE_PTABLES -Os -fomit-frame-pointer -I/usr/local/include/chicken
gcc 'scheme_imp.o' -o 'scheme_imp' -L/usr/local/lib -lchicken -lm
